services:
  ai:
    image: ai
    container_name: ai
    build: .
    env_file: .env
    ports:
      - "8083:8083"
    volumes:
      - .:/server
    command: ["fastapi", "run", "--host", "0.0.0.0", "--port", "8083", "server.py"]
