name: CI E-Learning

on:
    pull_request:
        branches:
            - develop
            - main
    push:
        branches:
            - develop
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:13
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: admin
                    PSOTGRES_DB: test
                ports:
                    - 5432:5432
            
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup environment
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install .

            - name: Set environment variables
              run: |
                echo "DB_HOST=localhost" >> $GITHUB_ENV
                echo "DB_PORT=5432" >> $GITHUB_ENV
                echo "DB_USER=postgres" >> $GITHUB_ENV
                echo "DB_PASSWORD=admin" >> $GITHUB_ENV
                echo "DB_DATABASE=test" >> $GITHUB_ENV

            - name: Run tests
              run: |
                python -m unittest discover -s tests -p "test_*.py"
                uvicorn server:app &
                SERVER_PID=$!

                sleep 3
                curl --fail http://localhost:8000/ || (echo "Server failed to start" && exit 1)
                trap "kill $SERVER_PID" EXIT
